### ISSUE TITLE
Failed to start Monkey Island Mongo Service

### ISSUE THREAD

**Issue by Parasimpaticki** [guardicore/monkey#40]
At first monkey-island.service wouldn't start but fixed it by removing bson
```
sudo pip uninstall bson
sudo pip uninstall pymongo
sudo pip install pymongo
```

But isn't starting also and I have no idea how to fix it
```
● monkey-island.service - Monkey Island Service
   Loaded: loaded (/lib/systemd/system/monkey-island.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-05-17 21:47:00 CEST; 5min ago
 Main PID: 5428 (start_server.sh)
    Tasks: 4 (limit: 4915)
   Memory: 19.8M
      CPU: 403ms
   CGroup: /system.slice/monkey-island.service
           ├─5428 /bin/bash /var/monkey_island/ubuntu/systemd/start_server.sh
           └─5429 python main.py

May 17 21:47:00 Broadband systemd[1]: Started Monkey Island Service.

● monkey-mongo.service - Monkey Island Mongo Service
   Loaded: loaded (/lib/systemd/system/monkey-mongo.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2017-05-17 21:47:02 CEST; 5min ago
  Process: 5501 ExecStop=/var/monkey_island/bin/mongodb/bin/mongod --shutdown (code=exited, status=127)
  Process: 5500 ExecStart=/var/monkey_island/bin/mongodb/bin/mongod --quiet --dbpath /var/monkey_island/db (code=exited, status=127)
 Main PID: 5500 (code=exited, status=127)
      CPU: 3ms

May 17 21:47:02 Broadband systemd[1]: monkey-mongo.service: Control process exited, code=exited status=127
May 17 21:47:02 Broadband systemd[1]: monkey-mongo.service: Unit entered failed state.
May 17 21:47:02 Broadband systemd[1]: monkey-mongo.service: Failed with result 'exit-code'.
May 17 21:47:02 Broadband systemd[1]: monkey-mongo.service: Service hold-off time over, scheduling restart.
May 17 21:47:02 Broadband systemd[1]: Stopped Monkey Island Mongo Service.
May 17 21:47:02 Broadband systemd[1]: monkey-mongo.service: Start request repeated too quickly.
May 17 21:47:02 Broadband systemd[1]: Failed to start Monkey Island Mongo Service.
May 17 21:47:02 Broadband systemd[1]: monkey-mongo.service: Unit entered failed state.
May 17 21:47:02 Broadband systemd[1]: monkey-mongo.service: Failed with result 'exit-code'.

```

**Comment by acepace** [comment]
Can you post your system configuration? Distribution, currently installed Python packages?

**Comment by Parasimpaticki** [comment]
Kali GNU/Linux Rolling, fully updated and here's list of my python packages https://pastebin.com/TjrKcLsX

**Comment by acepace** [comment]
Can you try the latest version of the Island code in github?

**Comment by danielguardicore** [comment]
Rewrote the monkey island deployment which should fix this.

**Comment by EL1X1R06** [comment]
I am still getting the same error i.e failed with result exit code

**Comment by bigq4mayor83** [comment]
Running sudo apt-get install mongodb fixed this for me.
